name: Deploy

on:
  push:
    branches: [ main ]

jobs:
  Deploy:
      
      name: Build Push Deploy
      runs-on: ubuntu-latest

    
      steps:

      - name: Check out code
        uses: actions/checkout@v2
      
      - name: Deploy to EC2
        env:
            PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
            HOSTNAME: ${{ vars.SSH_HOST }}
            USER_NAME: ${{ vars.USER_NAME }}
      
        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME} '

              # Say hi
              echo "Hi Ali"
              '