name: Deploy

on:
  push:
    branches: [ main ]

jobs:
  Deploy:
      
      name: Build Push Deploy
      runs-on: ubuntu-latest

    
      steps:

      - name: Check out code
        uses: actions/checkout@v2
      
      - name: Deploy to EC2
        env:
            PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
            HOSTNAME: ${{ vars.SSH_HOST }}
            USER_NAME: ${{ vars.USER_NAME }}
      
        run: |
          # create private key file
          echo "$PRIVATE_KEY" > ../private_key && chmod 600 ../private_key

          # use scp to copy the file to the server in app directory
          scp -o StrictHostKeyChecking=no -i ../private_key -r ./* ${USER_NAME}@${HOSTNAME}:/home/${USER_NAME}/app
          
          # use ssh to run commands on the server
          ssh -o StrictHostKeyChecking=no -i ../private_key ${USER_NAME}@${HOSTNAME} '

              # Say hi
              echo "Hi Ali"
              
              # pip install requirements
              pip3 install -r requirements.txt

              # kill the running app
              kill $(lsof -t -i:8080)

              # use uvicorn to run the app
              python3 -m uvicorn app.app:app --host 0.0.0.0 --port 8080
              '